package com.oa.entity;

import java.util.Date;

public class Org {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_PARENT_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Long orgParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.IS_PARENT
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Short isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_NAME
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_PATH
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private String orgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_DESC
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private String orgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.DISP_INDEX
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Short dispIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.STATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.CREATED_DATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    private Date createdDate;
    
    private String orgParentName;//当前组织的父组织名称

    public String getOrgParentName() {
		return orgParentName;
	}

	public void setOrgParentName(String orgParentName) {
		this.orgParentName = orgParentName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_ID
     *
     * @return the value of sys_org.ORG_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_ID
     *
     * @param orgId the value for sys_org.ORG_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_PARENT_ID
     *
     * @return the value of sys_org.ORG_PARENT_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Long getOrgParentId() {
        return orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_PARENT_ID
     *
     * @param orgParentId the value for sys_org.ORG_PARENT_ID
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setOrgParentId(Long orgParentId) {
        this.orgParentId = orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.IS_PARENT
     *
     * @return the value of sys_org.IS_PARENT
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Short getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.IS_PARENT
     *
     * @param isParent the value for sys_org.IS_PARENT
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setIsParent(Short isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_NAME
     *
     * @return the value of sys_org.ORG_NAME
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_NAME
     *
     * @param orgName the value for sys_org.ORG_NAME
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_PATH
     *
     * @return the value of sys_org.ORG_PATH
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public String getOrgPath() {
        return orgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_PATH
     *
     * @param orgPath the value for sys_org.ORG_PATH
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setOrgPath(String orgPath) {
        this.orgPath = orgPath == null ? null : orgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_DESC
     *
     * @return the value of sys_org.ORG_DESC
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public String getOrgDesc() {
        return orgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_DESC
     *
     * @param orgDesc the value for sys_org.ORG_DESC
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc == null ? null : orgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.DISP_INDEX
     *
     * @return the value of sys_org.DISP_INDEX
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Short getDispIndex() {
        return dispIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.DISP_INDEX
     *
     * @param dispIndex the value for sys_org.DISP_INDEX
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setDispIndex(Short dispIndex) {
        this.dispIndex = dispIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.STATE
     *
     * @return the value of sys_org.STATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.STATE
     *
     * @param state the value for sys_org.STATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.CREATED_DATE
     *
     * @return the value of sys_org.CREATED_DATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.CREATED_DATE
     *
     * @param createdDate the value for sys_org.CREATED_DATE
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}