package com.oa.mapper;

import java.util.List;
import java.util.Map;

import com.oa.entity.Area;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    int deleteByPrimaryKey(Long areaPriId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    Area selectByPrimaryKey(Long areaPriId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbggenerated Fri Jun 16 02:48:51 CST 2017
     */
    int updateByPrimaryKey(Area record);
    
	public    List<Map<String, Object>>  selectAreaByParentId(String parentId);

}