package com.oa.mapper;

import java.util.List;
import java.util.Map;

import com.oa.entity.Menu;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    Menu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKey(Menu record);
     public List<Menu>  selectMenuByRoleId(List roleIdList);    
    
     public  List<Menu> selectMenuListByPage(Map<String, Object> paramMap);
     public long selectTotalCount(Map<String, Object> paramMap);
      
     
     /**
      * 查询菜单的父目录
      */
     public   List<Menu> selectDirByParentId(long parentId);
      
     /**查看当前菜单及父目录名称
      * 
      * @param menuId
      * @return
      */
    public Menu selectMenuAndParenMenuByMenuId(long menuId);
    
    /**
     *角色下的授权菜单
     *     */
    public List<Menu> selectRoleMenuList(Map<String, Object> paramMap);
    public int  selectRoleMenuListCount(Map<String, Object> paramMap);
    
    
    public  List<Menu> selectMenuByParentId(long menuParentId);

}