package com.oa.mapper;

import java.util.List;
import java.util.Map;

import com.oa.entity.Org;
import com.oa.entity.Role;

public interface OrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     *新增
     */
    int insert(Map<String, Object> paramMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    Org selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 23:51:06 CST 2017
     */
    int updateByPrimaryKey(Org record);

    
	List<Org> selectOrgByPage(Map<String, Object> paramMap);

	long selectTotalCount(Map<String, Object> paramMap);
	
	/**
	 * 树形结构
	 */
	public List<Org> selectOrgListByParentId(long parentId);
	
	public long selectOrgId();
	
	  /**
     * 查询当前组织及父组织
     */
    Org selectOrgAndParentByOrgId(long orgId);
    
    int selectOrgIdByOrgName(String orgName);
    
    /**
     * 角色组织列表
     */
    public List<Org> selectRoleOrgList(Map<String, Object> paramMap);
    public int  selectRoleOrgListCount(Map<String, Object> paramMap);
    
	
}