package com.oa.mapper;

import java.util.List;

import com.oa.entity.RoleUserRel;

public interface RoleUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int deleteByPrimaryKey(Long roleUserRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insert(RoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insertSelective(RoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    RoleUserRel selectByPrimaryKey(Long roleUserRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKeySelective(RoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKey(RoleUserRel record);

	String selectRoleIdByUserId(long userId);
	
	/**
	 * 根据角色编号查询与用户的关系
	 * @param roleId
	 * @return
	 */
	List<RoleUserRel> selectUserByRoleId(long roleId);
	
	
}