package com.oa.mapper;

import com.oa.entity.RoleOrgRel;

public interface RoleOrgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int deleteByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insert(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int insertSelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    RoleOrgRel selectByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKeySelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Wed Jun 07 01:42:53 CST 2017
     */
    int updateByPrimaryKey(RoleOrgRel record);

	String selectRoleIdByOrgId(long orgId);
	
	
	public int deleteRoleOrgRel(int orgId);
}