package com.oa.mapper;

import java.util.List;
import java.util.Map;

import com.oa.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    User login(User user);
    
    List<User> selectUserListByOrgId(long orgId);
    
    public List<Map<String, Object>> selectProvinceNameAndCount();
    
    
    public List<Map<String, Object>> selectProviceAndSex();
    
    
    /**
     * 分页+条件查询
     */
    public List<User> selectUserListByPage(Map<String, Object> paramMap);
    public long selectUserCount(Map<String, Object> paramMap);
    
    /**
     * excel导出
     */
    public List<Map<String, Object>>  exportUsers();
    /**
     * 导入excel
     */
    public int importUsers(List<Map<String, Object>> list);
    
    /**
     *角色 用户列表   分页
     */
    public  List<User> selectRoleUserList(Map<String, Object> paramMap);
    public  int selectRoleUserListCount(Map<String, Object> paramMap);

    
}