package com.oa.service;

import java.util.List;
import java.util.Map;

import com.oa.entity.Menu;

public interface MenuService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    Menu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int updateByPrimaryKey(Menu record);
    public List<Menu>  selectMenuByRoleId(List roleIdList);  
    
    
    /**
     * 分页
     */
    public  Map<String, Object> selectMenuListByPage(Map<String, Object> paramMap);

    public  List<Menu> selectDirByParentId(long parentId);
    
    public Menu selectMenuAndParenMenuByMenuId(long menuId);
    
    public  Map<String, Object>  selectRoleMenuList(Map<String, Object> paramMap);
    /**
     * 查询所有的菜单目录及菜单
     * @param menuParentId
     * @return
     */
    public  List<Menu> selectMenuByParentId(long menuParentId);


}