package com.oa.service;

import java.util.List;
import java.util.Map;

import com.oa.entity.Org;

public interface OrgService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 21:47:59 CST 2017
     */
    int deleteByPrimaryKey(Long orgId);

    int insert(Map<String, Object> paramMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 21:47:59 CST 2017
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 21:47:59 CST 2017
     */
    Org selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 21:47:59 CST 2017
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Wed Jun 07 21:47:59 CST 2017
     */
    int updateByPrimaryKey(Org record);
    
     /**
      * 分页查询相关的两个方法
      */
//    public List<Org> selectOrgByPage(Map<String, Object> paramMap);
//    public long selectTotalCount(Map<String, Object> paramMap);
    
    public Map<String, Object> selectOrgList(Map<String, Object> paramMap);
    
	public List<Org> selectOrgListByParentId(long parentId);
	
	public long selectOrgId();
	
	  /**
     * 查询当前组织及父组织
     */
    Org selectOrgAndParentByOrgId(long orgId);
    
    int selectOrgIdByOrgName(String orgName);
    
    /**
     *  /**
     * 角色组织列表
     
    public List<Org> selectRoleOrgList(long roleId);
    public int  selectRoleOrgListCount(long roleId);
     */
    
    public Map<String, Object> selectRoleOrgList(Map<String, Object> paramMap);


    
}