package com.oa.service;

import com.oa.entity.RoleOrgRel;

public interface RoleOrgRelService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int deleteByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int insert(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int insertSelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    RoleOrgRel selectByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int updateByPrimaryKeySelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Tue Jun 06 23:47:41 CST 2017
     */
    int updateByPrimaryKey(RoleOrgRel record);
    
    public String selectRoleIdByOrgId(long orgId);
    
	public int deleteRoleOrgRel(int orgId);

}