package com.oa.service;

import java.util.List;
import java.util.Map;

import com.oa.entity.User;

public interface UserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 06 21:51:33 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    User login(User user);
    
    
    List<User> selectUserListByOrgId(long orgId);
    
    public Map<String, Object> selectProvinceNameAndCount();
    
    public Map<String, Object> selectProviceAndSex();
    
    /**
     * 分页+条件查询
     */
//    public List<User> selectUserListByPage(Map<String, Object> paramMap);
//    public long selectUserCount(Map<String, Object> paramMap);
    
    public Map<String, Object> selectUserListByPage(Map<String, Object> paramMap);

    /**
     * excel导出
     */
    public List<Map<String, Object>>  exportUsers();
    
    /**
     * 导入excel
     */
    public int InsertUsers(List<Map<String, Object>> list);
    
    public  Map<String, Object> selectRoleUserList(Map<String, Object> paramMap);

}